version: '3.8'

services:
  cron-svc:
    container_name: eg-cron
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.cron
    volumes:
      - "../sentieopackages:/sentieopackages"
      - "../charts:/charts"
      - "./src/cron:/app"
      - "./deployment/extras/crontab:/etc/cron.d/crontab"

  python2-svc:
    container_name: eg-py2
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.python2
    command: make run
    ports:
      - "8000:8000"
    volumes:
      - "../sentieopackages:/sentieopackages"
      - "./src/python2:/app"
      - "./deployment/runners/runpy2.sh:/run.sh"
