version: '3.8'

services:
  cron-svc:
    container_name: eg-cron
    build:
      context: ../
      dockerfile: ./setup-example/deployment/Dockerfile.cron
    volumes:
      - "./install-docker.sh:/install-docker.sh"
      - "${PWD}/${workdir}/src/cron:/app"
      - "${PWD}/${workdir}deployment/extras/crontab:/etc/cron.d/crontab"
