version: '3.8'

services:
  cron-svc:
    container_name: eg-cron
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.cron
    command: sh -c 'if [[ -z "" ]] ; then make run ; else tail -f /dev/null ; fi'
    volumes:
      - "./deployment/runners/runCron.sh:/run.sh"
      - "./src/cron:/app"
      - "./deployment/extras/crontab:/etc/cron.d/crontab"

  python2-svc:
    container_name: eg-py2
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.python2
    command: sh -c 'if [[ -z "" ]] ; then make run ; else tail -f /dev/null ; fi'
    ports:
      - "8000:8000"
    volumes:
      - "../sentieopackages:/sentieopackages"
      - "./src/python2:/app"
      - "./deployment/runners/runpy2.sh:/run.sh"

  # python3-svc:
  #   container_name: eg-py3
  #   build:
  #     context: ./
  #     dockerfile: ./deployment/Dockerfile.python3
  #   command: sh -c 'if [[ -z "" ]] ; then make run ; else tail -f /dev/null ; fi'
  #   ports:
  #     - "9000:8000"
  #   volumes:
  #     - "../sentieopackages:/sentieopackages"
  #     - "./src/python3:/app"
  #     - "./deployment/runners/runpy3.sh:/run.sh"
