version: '3.8'

services:
  cron-svc:
    container_name: eg-cron
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile.cron
    volumes:
      - "../sentieopackages:/sentieopackages"
      - "../charts:/charts"
      - "./src/cron:/app"
      - "./deployment/extras/crontab:/etc/cron.d/crontab"
